#!/usr/bin/env ruby
# Compile and upload content.

require File.join(File.dirname(__FILE__), 'config')

build :production
exec "rsync --recursive --delete --compress --progress --human-readable #{PUBLIC}/ #{UPLOAD_TO}"
