#!/bin/sh
# Run script/build automatically on any changes.
# It work only on Linux and require inotifywait (in Ubuntu you can install it by
# `sudo apt-get install inotify-tools`).

cd `dirname $0`
while true; do
    ./build
    inotifywait -re MOVE_SELF,MODIFY,CLOSE_WRITE ../
    sleep 1
done
