name: Preview
on:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Notify about new deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview-${{ github.event.number }}
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --production --frozen-lockfile
      - name: Build static files
        run: pnpm build
      - name: Check files changes
        id: hash
        run: ./node_modules/.bin/ssdeploy changed
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
      - name: Auth Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      - name: Install Google Cloud
        if: "!steps.hash.outputs.noChanges"
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy files
        id: deploy
        if: "!steps.hash.outputs.noChanges"
        run: ./node_modules/.bin/ssdeploy preview $PR --verbose
        env:
          PR: ${{ github.event.number }}
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.deploy.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
